workflows:
  ios-workflow:
    name: iOS Production
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      node: 16.x
      xcode: 14.2 # 使用您本地已有的Xcode版本
      vars:
        BUNDLE_ID: "com.zziot.app" # 从您的app.json中获取
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zziot.app
    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: 安装依赖
        script: |
          npm install
          cd ios && pod install --repo-update
      - name: 构建iOS应用
        script: |
          cd ios
          xcodebuild -workspace app.xcworkspace -scheme app -configuration Release -archivePath app.xcarchive archive
          xcodebuild -exportArchive -archivePath app.xcarchive -exportOptionsPlist exportOptions.plist -exportPath IPA
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID 